### ISSUE TITLE
Use composer

### ISSUE THREAD

**Issue by cfoellmann** [Varying-Vagrant-Vagrants/vvv-utilities#1]
Like I already said in the VVV repo I would recommend installing all packages via composer that are possible.
This way we can set things to version `*` and just let it get updated automatically.

**Comment by LoreleiAurora** [comment]
If we install with `composer create-project` how do we update?
It was my understanding that you couldn't without removing the dir and running create project again. Correct me if i'm wrong.

**Comment by jeremyfelt** [comment]
Hi @cfoellmann! I'm going to close this issue so that we can keep things central on the primary VVV repository. Hopefully we can have that all documented at some point.

I haven't previously understood how we can manage all of these utilities with composer. Can you open a new issue on VVV that describes how long term management might be possible (and better) than what we have now?
